Document: mingw-w64-gettext
Title: Debian mingw-w64-gettext Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-gettext is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-gettext/mingw-w64-gettext.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-gettext/mingw-w64-gettext.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-gettext/mingw-w64-gettext.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-gettext/html/index.html
Files: /usr/share/doc/mingw-w64-gettext/html/*.html
